### ISSUE TITLE
rostopic echo problem & how to visualize my own rosbag in DreamView? 

### ISSUE THREAD

**Issue by lygincn** [ApolloAuto/apollo#5544]
**System information:**
OS Platform and Distribution (Linux Ubuntu 14.04):
Apollo installed from (source):
Apollo version (3.0):

**Steps to reproduce the issue:**

0. get into dev_container
1. start roscore
2. rosbag play 2017-06-15-13-03-58_filterd.bag --loop (which is a rosbag containing the gps-data from ublox with the info below):
![rosdata](https://user-images.githubusercontent.com/40354939/44777243-aeca0580-abac-11e8-940c-e129e836e8c2.png)
3. rostopic echo [topic showed in the info picture above]

**Problem:**
only the two topics /Raw_Curvature_sensor [std_msgs/Float32MultiArray], /ublox_gps/fix [sensor_msgs/NavSatFix] can be echoed with the massages below:
```
header: 
  seq: 25
  stamp: 
    secs: 1497524645
    nsecs: 594009119
  frame_id: gps
status: 
  status: 0
  service: 1
latitude: 51.0356254
longitude: 13.7393869
altitude: 183.797
position_covariance: [7.584516, 0.0, 0.0, 0.0, 7.584516, 0.0, 0.0, 0.0, 12.299049]
position_covariance_type: 2
```

```
layout: 
  dim: 
    - 
      label: yaw__lat__steer__spdms
      size: 4
      stride: 1
  data_offset: 0
data: [0.02500000037252903, 0.06666681170463562, -1.5010906457901, 0.0]

```

the other three topics /ublox_gps/navposllh [ublox_msgs/NavPOSLLH], /ublox_gps/navvelned [ublox_msgs/NavVELNED], /ublox_gps/rxmraw [ublox_msgs/RxmRAW] all reported error below:
```
/use_sim_time is not set, will not subscribe to simulated time [/clock] topic
ERROR: Cannot load message class for [ublox_msgs/NavVELNED]. Are your messages built?

```
**Questions:**
1. why do topics from the same rosbag work differently with "rostopic echo" im Apollo? it appears to have something to do with the massage type. But what is the reason exactly?
2. how can I deal with this problem? actually i'm trying to play this rosbag in dreamview, is it even possible?
any comments are appreciated. Thanks. :)
